### ISSUE TITLE
Error on synology

### ISSUE THREAD

**Issue by koen01** [arvydas/blinkstick-python#21]
I get an error when trying my blinkstick on a Synology D213j.
See the python error below;
Dmesg shows this:
[366402.501085] usb 1-1: new low-speed USB device number 3 using ehci_marvell
[366402.742338] Get empty minor:104
[366402.764126] generic-usb 0003:20A0:41E5.0002: hiddev0: USB HID v1.01 Device [Agile Innovative Ltd BlinkStick] on usb-ehci_marvell.0-1/input0

Any ideas as to resolve this?

DiskStation> blinkstick --pulse --set-color blue
BlinkStick control script 0.7.0
(c) Agile Innovative Ltd 2013

Traceback (most recent call last):
  File "/usr/local/bin/blinkstick", line 5, in <module>
    pkg_resources.run_script('BlinkStick==0.7.0', 'blinkstick')
  File "/usr/local/packages/@appstore/Python/usr/local/lib/python2.7/site-packages/pkg_resources.py", line 499, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/local/packages/@appstore/Python/usr/local/lib/python2.7/site-packages/pkg_resources.py", line 1235, in run_script
    execfile(script_filename, namespace, namespace)
  File "/usr/local/packages/@appstore/Python/usr/local/lib/python2.7/site-packages/BlinkStick-0.7.0-py2.7.egg/EGG-INFO/scripts/blinkstick", line 340, in <module>
    sys.exit(main())
  File "/usr/local/packages/@appstore/Python/usr/local/lib/python2.7/site-packages/BlinkStick-0.7.0-py2.7.egg/EGG-INFO/scripts/blinkstick", line 248, in main
    sticks = blinkstick.find_all()
  File "/usr/local/lib/python2.7/site-packages/BlinkStick-0.7.0-py2.7.egg/blinkstick/blinkstick.py", line 397, in find_all
    return [BlinkStick(device=d) for d in _find_blicksticks()]
  File "/usr/local/lib/python2.7/site-packages/BlinkStick-0.7.0-py2.7.egg/blinkstick/blinkstick.py", line 35, in __init__
    self.open_device(device)
  File "/usr/local/lib/python2.7/site-packages/BlinkStick-0.7.0-py2.7.egg/blinkstick/blinkstick.py", line 358, in open_device
    if self.device.is_kernel_driver_active(0):
  File "/usr/local/packages/@appstore/Python/usr/local/lib/python2.7/site-packages/usb/core.py", line 704, in is_kernel_driver_active
    return self._ctx.backend.is_kernel_driver_active(self._ctx.handle, interface)
  File "/usr/local/packages/@appstore/Python/usr/local/lib/python2.7/site-packages/usb/backend/__init__.py", line 355, in is_kernel_driver_active
    _not_implemented(self.is_kernel_driver_active)
  File "/usr/local/packages/@appstore/Python/usr/local/lib/python2.7/site-packages/usb/backend/__init__.py", line 79, in _not_implemented
    raise NotImplementedError(func.__name__)
NotImplementedError: is_kernel_driver_active

**Comment by Conan-Kudo** [comment]
@arvydas is this still an issue with [pyusb 1.0.0rc1](https://pypi.python.org/pypi/pyusb)? It was recently released and it'd be good to know if it's still an issue...
